### ISSUE TITLE
Highest NA% not indicated on the key

### ISSUE THREAD

**Issue by BKGiwa** [TeamMacLean/pepdiff#2] opened 2024-01-12 11:01 UTC
* Examining missing peptides
* => The key for the lightest (highest) missing value is not indicated

**Comment by danmaclean** [comment] 2024-01-15 11:07
Thanks for this Tife, Looks like I don't have any code that can reproduce your issue, please could you write out the issue in full so that I can see specifically what your error is about. If possible create a reprex that causes it.

Thanks
Dan

**Comment by BKGiwa** [comment] 2024-01-16 15:40
Hi Dan,

The problem occurred under the "Data Checks" section, specifically when examining the percentage of missing peptides recorded at different time points. The main issue lies in the absence of an indicated key for the highest percentage of missing value.

Required package:
```
library(pepdiff)
```

Load raw data:

  ```
example_data <- import_data(
  here::here("raw", "reprex_frank.csv"),
  gene_id = "protein_name",
  treatment = "genotype",
  seconds = "timepoints",
  peptide = "new_annot",
  bio_rep = "bio_rep",
  tech_rep = "tech_rep",
  quant = "timepoints_values"
)
```

Code snippet (where the problem lies):
```
plot_missing_peptides(example_data)
```

The link to the dummy data:
[reprex_frank.csv](https://github.com/TeamMacLean/pepdiff/files/13952287/reprex_frank.csv)

Expected behaviour:
I expected that the key would display all the colours in the figure.

Actual behaviour:
The lightest colour (yellow) which represents the highest NA recorded was not shown on the key.

**Comment by danmaclean** [comment] 2024-01-17 11:08
Hi Tife,

Thanks for providing this, should be fixed in 

https://github.com/TeamMacLean/pepdiff/commit/7a1441701243b1155f218285993d59c1475c6a26

**Closed as completed by danmaclean** 2024-01-17 11:08 UTC
